TARGET_DEVICE := wp12pro

BOARD_BOOTIMAGE_PARTITION_SIZE := 32M
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2048M
BOARD_VENDORIMAGE_PARTITION_SIZE := 1024M

BOARD_HAS_LCM := true
BOARD_LCM_WIDTH := 720
BOARD_LCM_HEIGHT := 1440
BOARD_LCM_DENSITY := 272

TARGET_KERNEL_USE_PREBUILT := true
